Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu2204"
  
    config.vm.provider "virtualbox" do |v|
      v.memory = 8192
      v.cpus = 4
    end
  
    config.vm.synced_folder "data", "/home/vagrant/workspace"
  
    config.vm.network "forwarded_port", guest: 8080, host: 8080
    config.vm.network "forwarded_port", guest: 5000, host: 5000
    config.vm.network "forwarded_port", guest: 9870, host: 9870
    config.vm.network "forwarded_port", guest: 8088, host: 8088
  
    config.vm.provision "shell", inline: <<-SHELL
      apt-get update
      curl -sSL https://get.docker.com/ | sh
      apt install -y docker-compose
      sudo usermod -aG docker vagrant
    SHELL
  end