Vagrant.configure("2") do |config|
  # Imagen base: Ubuntu 26.04 LTS
  config.vm.box = "bento/ubuntu-26.04"

  # Configuración del proveedor VirtualBox
  config.vm.provider "virtualbox" do |vb|
    vb.name = "docker-vm"
    vb.memory = 8192
    vb.cpus = 4
  end

  # Carpeta compartida entre host y VM
  config.vm.synced_folder "vm-workspace", "/home/vagrant/vm-workspace"

  # Puertos expuestos
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 5000, host: 5000
  # HDFS
  config.vm.network "forwarded_port", guest: 9870, host: 9870
  config.vm.network "forwarded_port", guest: 9864, host: 9864
  config.vm.network "forwarded_port", guest: 8020, host: 8020
  # MinIO
  config.vm.network "forwarded_port", guest: 9000, host: 9000
  config.vm.network "forwarded_port", guest: 9001, host: 9001

  # Instalación de Docker y Docker Compose
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update -y
    curl -fsSL https://get.docker.com/ | sh
    sudo apt-get install -y docker-compose
    sudo usermod -aG docker vagrant
  SHELL
end